### ISSUE TITLE
\Sineflow\ClamAV\Socket\Socket sends to ClamAV Server only file path instead data 

### ISSUE THREAD

**Issue by svinohod** [sineflow/clamav#7]
PHP 8.1
Symfony 6.3
sineflow/clamav 1.1.1

Configuration:
```
sineflow_clam_av:
  strategy: clamd_network
  host: '%env(CLAMAV_HOST)%'
  port: '%env(CLAMAV_PORT)%'
```

Inside `\Sineflow\ClamAV\Socket\Socket::sendCommand` contains $dataIn value `SCAN /var/www/html/tests/resources/test-1-original.jpg` instead file data.
